default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("PGUSER") %>
  password: <%= ENV.fetch("PGPASSWORD") %>
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: gmailFake_development

test:
  <<: *default
  database: gmailFake_test

production:
  <<: *default
  database: gmailFake_production
  username: <%= ENV.fetch("PGUSER") %>
  password: <%= ENV.fetch("PGPASSWORD") %>
